checkdir  $BASH_SOURCE:$LINENO out/foo_androidsdk_jar/res
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_jar/res/org/smart/test/foo/R.java
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_jar/foo_androidsdk_jar.jar
checkdir  $BASH_SOURCE:$LINENO out/foo_androidsdk_jar/classes
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_jar/classes/org/smart/test/foo/Foo.class
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_jar/classes/org/smart/test/foo/R.class
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_jar/classes/org/smart/test/foo/R\$attr.class
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_jar/classes/org/smart/test/foo/R\$id.class
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_jar/classes/org/smart/test/foo/R\$layout.class
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_jar/classes/org/smart/test/foo/R\$string.class
