checkdir  $BASH_SOURCE:$LINENO $out/foo_androidsdk_use_jar/res
checkfile $BASH_SOURCE:$LINENO $out/foo_androidsdk_use_jar/res/org/smart/test/R.java
checkfile $BASH_SOURCE:$LINENO $out/foo_androidsdk_use_jar/foo_androidsdk_use_jar.apk
checkfile $BASH_SOURCE:$LINENO $out/foo_androidsdk_use_jar/unsigned.apk
checkdir  $BASH_SOURCE:$LINENO $out/foo_androidsdk_use_jar/classes
checkfile $BASH_SOURCE:$LINENO $out/foo_androidsdk_use_jar/classes.dex
checkfile $BASH_SOURCE:$LINENO $out/foo_androidsdk_use_jar/classes/org/smart/test/Foobar.class
checkfile $BASH_SOURCE:$LINENO $out/foo_androidsdk_use_jar/classes/org/smart/test/R.class
checkfile $BASH_SOURCE:$LINENO $out/foo_androidsdk_use_jar/classes/org/smart/test/R\$attr.class
checkfile $BASH_SOURCE:$LINENO $out/foo_androidsdk_use_jar/classes/org/smart/test/R\$layout.class
checkfile $BASH_SOURCE:$LINENO $out/foo_androidsdk_use_jar/classes/org/smart/test/R\$string.class
