checkdir  $BASH_SOURCE:$LINENO out/foo_androidsdk_apk/res
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_apk/res/org/smart/test/ASDK/R.java
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_apk/foo_androidsdk_apk.apk
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_apk/unsigned.apk
checkdir  $BASH_SOURCE:$LINENO out/foo_androidsdk_apk/classes
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_apk/classes.dex
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_apk/classes/org/smart/test/ASDK/Foo.class
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_apk/classes/org/smart/test/ASDK/R.class
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_apk/classes/org/smart/test/ASDK/R\$attr.class
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_apk/classes/org/smart/test/ASDK/R\$layout.class
checkfile $BASH_SOURCE:$LINENO out/foo_androidsdk_apk/classes/org/smart/test/ASDK/R\$string.class
